<h1>edit a meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?><br>

<?= $this->formRow($form->get('title')) ?><br>

<?= $this->formRow($form->get('description')) ?><br>

<?= $this->formRow($form->get('date_debut')) ?><br> <?= $this->msg; ?> <br>

<?= $this->formRow($form->get('date_fin')) ?><br>

<?= $this->formInput($form->get('submit')) ?>

<?= $this->form()->closeTag($form); ?>
